spring:
  kafka:
    bootstrap-servers: localhost:9092
    Key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: my-group
#      auto-offset-reset: earliest
#      enable-auto-commit: false

camel:
  components:
    kafka:
      brokers: localhost:9092
      consumer:
        group-id: my-group
#        auto-offset-reset: earliest
#        enable-auto-commit: false
    springboot:
        main-run-controller: true